#pragma once

#include <network/core/network_core.h>

namespace gl {

    enum NetworkCode : int {

        // general error codes

        NONE = 0,
        NOT_IMPLEMENTED = -1,
        SOCKET_OPTION_NOT_SUPPORTED = -2,

        // platform specific error codes

#ifdef WINDOWS

        SOCKET = SOCKET_ERROR,
        SOCKET_INVALID = WSA_INVALID_HANDLE,
        OUT_OF_MEMORY = WSA_NOT_ENOUGH_MEMORY,
        INVALID_PARAMETER = WSA_INVALID_PARAMETER,
//        INVALID_EVENT = WSA_INVALID_EVENT,
        OPERATION_ABORTED = WSA_OPERATION_ABORTED,
        IO_INCOMPLETE = WSA_IO_INCOMPLETE,
        IO_PENDING = WSA_IO_PENDING,
        CALL_INTERRUPTED = WSAEINTR,
        INVALID_FILE = WSAEBADF,
        PERMISSION_DENIED = WSAEACCES,
        ADDRESS_INVALID = WSAEFAULT,
        INVALID_ARGUMENT = WSAEINVAL,
        TOO_MANY_OPEN_FILES = WSAEMFILE,
        RESOURCE_TEMP_UNAVAILABLE = WSAEWOULDBLOCK,
        NOW_IN_PROGRESS = WSAEINPROGRESS,
        ALREADY_IN_PROGRESS = WSAEALREADY,
        INVALID_OPERATION = WSAENOTSOCK,
        DESTINATION_ADDRESS_REQUIRED = WSAEDESTADDRREQ,
        TOO_LONG_MESSAGE = WSAEMSGSIZE,
        WRONG_PROTOCOL_TYPE = WSAEPROTOTYPE,
        WRONG_PROTOCOL_OPTION = WSAENOPROTOOPT,
        PROTOCOL_NOT_SUPPORTED = WSAEPROTONOSUPPORT,
        SOCKET_NOT_SUPPORTED = WSAESOCKTNOSUPPORT,
        OPERATION_NOT_SUPPORTED = WSAEOPNOTSUPP,
        PROTOCOL_FAMILY_NOT_SUPPORTED = WSAEPFNOSUPPORT,
        ADDRESS_FAMILY_NOT_SUPPORTED = WSAEAFNOSUPPORT,
        ADDRESS_IN_USE = WSAEADDRINUSE,
        ADDRESS_NOT_AVAILABLE = WSAEADDRNOTAVAIL,
        NETWORK_DEAD = WSAENETDOWN,
        NETWORK_UNREACHABLE = WSAENETUNREACH,
        NETWORK_DROP_CONNECTION_ON_RESET = WSAENETRESET,
        CONNECTION_ABORT = WSAECONNABORTED,
        CONNECTION_RESET = WSAECONNRESET,
        BUFFER_NO_SPACE = WSAENOBUFS,
        SOCKET_CONNECTED = WSAEISCONN,
        SOCKET_NOT_CONNECTED = WSAENOTCONN,
        SOCKET_SHUTDOWN = WSAESHUTDOWN,
        TOO_MANY_REFERENCES = WSAETOOMANYREFS,
        CONNECTION_TIMEOUT = WSAETIMEDOUT,
        CONNECTION_REFUSED = WSAECONNREFUSED,
        NAME_CANNOT_TRANSLATE = WSAELOOP,
        NAME_TOO_LONG = WSAENAMETOOLONG,
        HOST_SHUTDOWN = WSAEHOSTDOWN,
        HOST_NO_ROUTE = WSAEHOSTUNREACH,
        TOO_MANY_PROCESSES = WSAEPROCLIM,
        QUOTA_USER_EXCEEDED = WSAEUSERS,
        QUOTA_DISK_EXCEEDED = WSAEDQUOT,
        FILE_HANDLE_STALE = WSAESTALE,
        ITEM_IS_REMOTE = WSAEREMOTE,
        NETWORK_SUBSYSTEM_NOT_AVAILABLE = WSASYSNOTREADY,
        LIBRARY_VERSION_NOT_SUPPORTED = WSAVERNOTSUPPORTED,
        LIBRARY_NOT_INITIALIZED = WSANOTINITIALISED,
        SHUTDOWN_IN_PROGRESS = WSAEDISCON,
        NO_RESULTS = WSAENOMORE,
        CALL_CANCEL = WSAECANCELLED,
        CALL_INVALID_TABLE = WSAEINVALIDPROCTABLE,
        SERVICE_PROVIDER_INVALID = WSAEINVALIDPROVIDER,
        SERVICE_PROVIDER_NOT_INITIALIZED = WSAEPROVIDERFAILEDINIT,
        SYSTEM_CALL_FAILURE = WSASYSCALLFAILURE,
        SERVICE_NOT_FOUND = WSASERVICE_NOT_FOUND,
        TYPE_NOT_FOUND = WSATYPE_NOT_FOUND,
        QUERY_REFUSED = WSAEREFUSED,
        HOST_ISNT_FOUND = WSAHOST_NOT_FOUND,

#elif LINUX
#endif

    };

}